# Generated by Django 6.0.2 on 2026-02-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0002_projectmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.FileField(upload_to='projects/'),
        ),
    ]
