# Generated by Django 6.0.2 on 2026-02-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0003_alter_project_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_video',
            field=models.FileField(blank=True, null=True, upload_to='projects/videos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
