# Generated by Django 6.0.2 on 2026-02-22 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0004_project_featured_video_alter_project_featured_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectMessage',
        ),
    ]
