# Generated by Django 6.0.2 on 2026-02-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0007_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('service_category', models.CharField(choices=[('Civil Engineering', 'Civil Engineering'), ('Aluminum Fabrication', 'Aluminum Fabrication'), ('Curtain Walls', 'Curtain Walls / Cladding'), ('Telecommunications', 'Turnkey Cell Site Delivery'), ('Consultancy', 'General Consultancy'), ('Other', 'Other')], default='Civil Engineering', max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Mark as checked once you have contacted the client.')),
            ],
            options={
                'verbose_name': 'Project Inquiry',
                'verbose_name_plural': 'Project Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
