# Generated by Django 6.0.2 on 2026-02-22 11:33

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0008_projectinquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinquiry',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter number with +country code', max_length=128, null=True, region=None),
        ),
    ]
