# Generated by Django 6.0.2 on 2026-02-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0010_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinquiry',
            name='reference_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
