# Generated by Django 6.0.2 on 2026-02-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0013_alter_booking_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinquiry',
            name='service_category',
            field=models.CharField(choices=[('Civil Engineering', 'Civil Engineering'), ('Aluminum Fabrication', 'Aluminum Fabrication'), ('Curtain Walls', 'Curtain Walls / Cladding'), ('Telecommunications', 'Turnkey Cell Site Delivery'), ('Consultancy', 'General Consultancy'), ('Testimony', 'Testimony'), ('Other', 'Other')], default='Civil Engineering', max_length=50),
        ),
    ]
